#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
install_root="${XDG_DATA_HOME:-$HOME/.local/share}/open-osint-kit"
venv_dir="$install_root/venv"
bin_dir="$HOME/.local/bin"
wrapper="$bin_dir/osint-kit"
purge_generated_data=false

if [[ -t 0 ]]; then
    read -r -p "Also delete generated build artifacts and the stored Shodan key? [y/N] " purge_answer
    if [[ "$purge_answer" =~ ^[Yy]([Ee][Ss])?$ ]]; then
        purge_generated_data=true
    fi
else
    printf 'Non-interactive session detected; generated artifacts and Shodan key will be kept.\n'
fi

if [[ -f "$install_root/path-config" ]]; then
    shell_config="$(<"$install_root/path-config")"
    case "$shell_config" in
        "$HOME/.bashrc"|"$HOME/.zshrc"|"$HOME/.profile")
            printf -v escaped_bin_dir '%q' "$bin_dir"
            path_line="export PATH=$escaped_bin_dir:\$PATH"
            if [[ -f "$shell_config" ]]; then
                temp_config="$(mktemp "${shell_config}.XXXXXX")"
                if awk -v path_line="$path_line" '$0 != path_line' "$shell_config" > "$temp_config"; then
                    mv -- "$temp_config" "$shell_config"
                else
                    rm -f -- "$temp_config"
                    printf 'Could not update %s; review the PATH line manually.\n' "$shell_config" >&2
                    exit 1
                fi
            fi
            ;;
        *)
            printf 'Kept the unrecognized shell configuration path recorded in path-config.\n' >&2
            ;;
    esac
else
    printf 'No record of a PATH line added by this installation; keeping shell configuration.\n'
fi

if [[ -f "$wrapper" ]]; then
    printf -v expected_wrapper '#!/usr/bin/env bash\nexec %q "$@"' "$venv_dir/bin/osint-kit"
    actual_wrapper="$(<"$wrapper")"
    if [[ "$actual_wrapper" == "$expected_wrapper" ]]; then
        rm -- "$wrapper"
    else
        printf 'Kept %s because it does not match the launcher generated by the installer.\n' "$wrapper"
    fi
fi

if [[ "$purge_generated_data" == true ]]; then
    if [[ -x "$venv_dir/bin/python" ]]; then
        if "$venv_dir/bin/python" -c "import keyring; keyring.delete_password('open-osint-kit', 'shodan-api-key')" >/dev/null 2>&1; then
            printf 'Removed the stored Shodan key from the OS keyring.\n'
        else
            printf 'The Shodan key could not be removed from the OS keyring; remove it manually if needed.\n'
        fi
    fi
    for artifact in "$script_dir/build" "$script_dir/dist" "$script_dir/open_osint_kit.egg-info" "$script_dir/__pycache__"; do
        if [[ -e "$artifact" ]]; then
            rm -rf -- "$artifact"
            printf 'Removed generated artifact: %s\n' "$artifact"
        fi
    done
else
    printf 'Kept generated build artifacts and the Shodan key.\n'
fi

if [[ -d "$venv_dir" ]]; then
    rm -rf -- "$venv_dir"
fi
rm -f -- "$install_root/path-config"
rmdir -- "$install_root" 2>/dev/null || true

printf 'Open OSINT Kit was uninstalled. Other user files and tools were preserved.\n'
printf 'Open a new terminal to apply any PATH changes.\n'
