#!/usr/bin/env bash
set -euo pipefail

install_root="${XDG_DATA_HOME:-$HOME/.local/share}/open-osint-kit"
venv_dir="$install_root/venv"
bin_dir="$HOME/.local/bin"
wrapper="$bin_dir/osint-kit"

if [[ -f "$install_root/path-config" ]]; then
    shell_config="$(<"$install_root/path-config")"
    case "$shell_config" in
        "$HOME/.bashrc"|"$HOME/.zshrc"|"$HOME/.profile")
            printf -v escaped_bin_dir '%q' "$bin_dir"
            path_line="export PATH=$escaped_bin_dir:\$PATH"
            if [[ -f "$shell_config" ]]; then
                temp_config="$(mktemp "${shell_config}.XXXXXX")"
                if awk -v path_line="$path_line" '$0 != path_line' "$shell_config" > "$temp_config"; then
                    mv -- "$temp_config" "$shell_config"
                else
                    rm -f -- "$temp_config"
                    printf 'Could not update %s; review the PATH line manually.\n' "$shell_config" >&2
                    exit 1
                fi
            fi
            ;;
        *)
            printf 'Kept the unrecognized shell configuration path recorded in path-config.\n' >&2
            ;;
    esac
else
    printf 'No record of a PATH line added by this installation; keeping shell configuration.\n'
fi

if [[ -f "$wrapper" ]]; then
    printf -v expected_wrapper '#!/usr/bin/env bash\nexec %q "$@"' "$venv_dir/bin/osint-kit"
    actual_wrapper="$(<"$wrapper")"
    if [[ "$actual_wrapper" == "$expected_wrapper" ]]; then
        rm -- "$wrapper"
    else
        printf 'Kept %s because it does not match the launcher generated by the installer.\n' "$wrapper"
    fi
fi

if [[ -d "$venv_dir" ]]; then
    rm -rf -- "$venv_dir"
fi
rm -f -- "$install_root/path-config"
rmdir -- "$install_root" 2>/dev/null || true

printf 'Open OSINT Kit was uninstalled. Other user files and tools were preserved.\n'
printf 'Open a new terminal to apply any PATH changes.\n'
